<html>
	<?php include 'header.php';?>
	<title>Risk Factors: Litigation</title>
	<body>
		<?php include 'navigation.php';?>
		<div id="PageContainerOuter">
			<div id="PageContainer">
				<div id="HomeGalleryNavigation">
                    
                    <?php
                        include 'Banners/Banner8/index.html'; 
                    ?>

                </div>
				<div class="inner">
					<div class="style1">Risk Factors: Litigation</div>
					</br>
					<span class="style2">We may have claims and lawsuits against us that may result in adverse outcomes.</span>
					</br>
					We will be possibly subject to a variety of claims and lawsuits. Adverse outcomes in some or all of these claims may result in significant monetary damages or injunctive relief that could adversely affect our ability to conduct our business. The litigation and other claims are subject to inherent uncertainties and management’s view of these matters may change in the future. A material adverse impact on our financial statements also could occur for the period in which the effect of an unfavorable final outcome becomes probable and reasonably estimable. 
					</br></br>
					<span class="style2">We may be subject to legal liability associated with providing online services or content.</span>
					</br>
					We may provide a wide variety of services and products that enable users to exchange information, advertise products and services, conduct business, and engage in various online activities both domestically and internationally. The law relating to the liability of providers of these online services and products for activities of their users is still unsettled both within the U.S. and internationally. Claims have been threatened and have been brought against us for defamation, negligence, breaches of contract, copyright or trademark infringement, unfair competition, unlawful activity, tort, including personal injury, fraud, or other theories based on the nature and content of information which we publish or to which we provide links or that may be posted online or generated by us or by third parties, including our users. In addition, we are and have been and may again in the future be subject to domestic or international actions alleging that certain content we have generated or third-party content that we have made available within our services violates laws in domestic and international jurisdictions.
					</br></br>
					We also arrange for the distribution of third-party advertisements to third-party publishers and advertising networks, and we offer third-party products, services, or content. We may be subject to claims concerning these products, services, or content by virtue of our involvement in marketing, branding, broadcasting, or providing access to them, even if we do not ourselves host, operate, provide, or provide access to these products, services, or content. Defense of any such actions could be costly and involve significant time and attention of our management and other resources, may result in monetary liabilities or penalties, and may require us to change our business in an adverse manner.
					</br></br>
					<span class="style2">We May Be Subject to Product Liability Claims if People or Property Are Harmed by the Products Sell or Offer through the FSR Program</span>
					</br>
					Some of the products we sell or manufacture may expose us to product liability claims relating to personal injury, death, or environmental or property damage, and may require product recalls or other actions. Certain third parties also sell products using our e-commerce platform that may increase our exposure to product liability claims, such as if these sellers do not have sufficient protection from such claims. Although we will continually maintain liability insurance, we cannot be certain that our coverage will be adequate for liabilities actually incurred or that insurance will continue to be available to us on economically reasonable terms, or at all. In addition, some of our agreements with our vendors and sellers do may not indemnify us from product liability.
					</br></br>
					<span class="style2">We are regularly subject to claims, suits, government investigations, and other proceedings that may result in adverse outcomes.</span>
					</br>
					At any given time we are subject to claims, suits, government investigations, and other proceedings involving competition, intellectual property, privacy, consumer protection, tax, labor and employment, commercial disputes, content generated by our users, goods and services offered by advertisers or publishers using our platforms, and other matters. The sale and/or promotional giveaway of hardware products also expose us to the risk of product liability and other litigation involving assertions about product defects, as well as health and safety, hazardousmaterials usage, and other environmental concerns.
					</br></br>
					Such claims, suits, government investigations, and proceedings are inherently uncertain and their results cannot be predicted with certainty. Regardless of the outcome, such legal proceedings can have an adverse impact on us because of legal costs, diversion of management resources, and other factors. Determining reserves for our pending litigation is a complex, fact-intensive process that requires significant judgment. It is possible that a resolution of one or more such proceedings could result in substantial fines and penalties that could adversely affect the industry as a whole, our business, consolidated financial position, results of operations, or cash flows in a particular period. These proceedings could also result in reputational harm, criminal sanctions, consent decrees, or orders preventing us from offering certain features, functionalities, products, or services, requiring a change in our business practices or product recalls or other field action, or requiring development of non-infringing or otherwise altered products or technologies. Any of these consequences could adversely affect our business and results of operations.
					</br></br>
					<span class="style2">We May Not Be Able to Adequately Protect Our Intellectual Property Rights or May Be Accused of Infringing Intellectual Property Rights of Third Parties</span>
					</br>
					We regard our trademarks, service marks, copyrights, patents, trade dress, trade secrets, proprietary technology, and similar intellectual property as critical to our success, and we rely on trademark, copyright, and patent law, trade secret protection, and confidentiality and/or license agreements with our employees, customers, and others to protect our proprietary rights. Effective intellectual property protection may not be available in every country in which our products and services are made available. We also may not be able to acquire or maintain appropriate domain names in all countries in which we do business. Furthermore, regulations governing domain names may not protect our trademarks and similar proprietary rights. We may be unable to prevent third parties from acquiring domain names that are similar to, infringe upon, or diminish the value of our trademarks and other proprietary rights.
					</br></br>
					We may not be able to discover or determine the extent of any unauthorized use of our proprietary rights. Third parties that license our proprietary rights also may take actions that diminish the value of our proprietary rights or reputation. The protection of our intellectual property may require the expenditure of significant financial and managerial resources. Moreover, the steps we take to protect our intellectual property may not adequately protect our rights or prevent third parties from infringing or misappropriating our proprietary rights.
					</br></br>
					<span class="style2">We may be subject to product liability claims if people or property are harmed by the products we sell.</span>
					</br>
					Some of the products we sell or manufacture may expose us to product liability claims relating to personal injury, death, or environmental or property damage, and may require product recalls or other actions. Certain third parties also sell products using our e-commerce platform that may increase our exposure to product liability claims, such as if these sellers do not have sufficient protection from such claims. Although we maintain liability insurance, we cannot be certain that our coverage will be adequate for liabilities actually incurred or that insurance will continue to be available to us on economically reasonable terms, or at all. In addition, some of our agreements with our vendors and sellers do not indemnify us from product liability.
					</br></br>
					<span class="style2">We could be liable for fraudulent or unlawful activities of sellers.</span>
					</br>
					The law relating to the liability of providers of online payment services is currently unsettled. In addition, governmental agencies could require changes in the way this business is conducted. Under our seller programs, we may be unable to prevent sellers from collecting payments, fraudulently or otherwise, when buyers never receive the products they ordered or when the products received are materially different from the sellers’ descriptions. Under our proposed FSR and NeuroZone Guarantee, we reimburse buyers for payments up to certain limits in these situations, and as our marketplace seller sales grow, the cost of this program will increase and could negatively affect our operating results. We also may be unable to prevent sellers on our sites or through other seller sites from selling unlawful goods, from selling goods in an unlawful manner, or violating the proprietary rights of others, and could face civil or criminal liability for unlawful activities by our sellers.
					</br></br>
				</div>
			</div>
		</div>
	</body>
</html>