<html>
	<?php include 'header.php';?>
	<title>Risk Factors: Technology & Security</title>
	<body>
		<?php include 'navigation.php';?>
		<div id="PageContainerOuter">
			<div id="PageContainer">
				<div class="inner">
					<div class="style1">Risk Factors: Technology & Security</div>
					</br>
					<span class="style2">More people are using devices other than personal computers to access the internet and accessing new platforms to make search queries. If manufacturers and users do not widely adopt versions our mobile search technology developed for these devices, our business could be adversely affected.</span>
					</br>
					The number of people who access the internet through devices other than personal computers, including mobile phones, smartphones, handheld computers such as netbooks and tablets, video game consoles, and television set- top devices, has increased dramatically in the past few years. The lower resolution, functionality, and memory associated with some alternative devices could make the use of our products and services through such devices more difficult and the versions of our products and services developed for these devices may not be compelling to users, manufacturers, or distributors of alternative devices. Each manufacturer or distributor may establish unique technical standards for its devices, and our products and services may not work or be viewable on these devices as a result. In addition, search queries are increasingly being undertaken via “apps” tailored to particular devices or social media platforms, which could affect the users think about and use search technology. As new devices and platforms are continually being released, it is difficult to predict the problems we may encounter in adapting our products and services and developing competitive new products and services. We expect to continue to devote significant amounts of attention to the creation, support, and maintenance of mobile products and services. If we are unable to attract and retain a substantial number of alternative device manufacturers, distributors, and users to our products and services, or if we are slow to develop products and technologies that are more compatible with alternative devices and platforms, we will fail to capture the opportunities available as consumers and advertisers transition to a dynamic, multi-screen environment.
					</br></br>
					<span class="style2">Web spam and content farms could decrease our search quality, which could damage our reputation and deter our current and potential users from using our products and services.</span>
					</br>
					“Web spam” refers to websites that attempt to violate a search engine's quality guidelines or that otherwise seek to rank higher in search results than a search engine's assessment of their relevance and utility would rank them. Although English-language web spam in our service provider’s search results have been significantly reduced, and web spam in most other languages is limited, we expect web spammers will continue to seek ways to improve their rankings inappropriately. We continuously will be expected to combat web spam, including through indexing technology that makes it harder for spam-like, less useful web content to rank highly. We expect to face challenges from low-quality and irrelevant content websites, including “content farms,” which are websites that generate large quantities of low-quality content to help them improve their search rankings. Our provider continually is launching algorithmic changes focused on low-quality websites. If web spam and content farms continue to increase on search engines, this could hurt our reputation for delivering relevant information or reduce user traffic to our websites. In addition, as we continue to take actions to improve our search quality and reduce low-quality content. 
					</br></br>
					<span class="style2">Interruption or failure of our information technology and communications systems could hurt our ability to effectively provide our products and services, which could damage our reputation and harm our results.</span>
					</br>
					The availability of our products and services depends on the continuing operation of our information technology and communications systems. Our systems are vulnerable to damage or interruption from earthquakes, terrorist attacks, floods, fires, power loss, telecommunications failures, computer viruses, computer denial of service attacks, or other attempts to harm our systems. Some of our data centers are located in areas with a high risk of major earthquakes. Our data centers are also subject to break-ins, sabotage, and intentional acts of vandalism, and to potential disruptions if the operators of these facilities have financial difficulties. Some of our systems are not fully redundant, and our disaster recovery planning 
					</br></br>
					<span class="style2">Data security and attacks to our infrastructure are a constant and ongoing concern.</span>
					</br>
					Our users, suppliers and advertisers look upon us to keep their sensitive data they have entrusted to us safe from outsiders. A data breach or attack could have huge legal ramifications, as state, Federal and international regulatory authorities and private plaintiffs would quickly react. This could cause the company to lose focus on the operations of the company in an effort to defend itself. LinkedIn recently experienced these negative ramifications first hand as it was sued for $5 million in connection with its recent data breach.  The potential damage to our company’s brand and credibility could be significant.  
					</br></br>
					Maintaining the security of computers and computer networks is paramount for us and our customers. Threats to information technology security can take a variety of forms. Hackers develop and deploy viruses, worms, and other malicious software programs that attack our products and services and gain access to our networks and data centers. Groups of hackers may also act in a coordinated manner to launch distributed denial of service attacks, or other coordinated attacks. Sophisticated organizations, individuals, or governments launch targeted attacks to gain access to our network. Breaches of our network or data security could disrupt and compromise the security of our internal systems and business applications, impair our ability to provide services to our customers and protect the privacy of their data, result in product development delays, compromise confidential or technical business information harming our competitive position, result in theft or misuse of our intellectual property, or otherwise adversely affect our business.
					</br></br>
					In addition, our technology environment continues to evolve. We embrace new ways of sharing data and communicating internally and with partners and customers using methods such as social networking and other consumer-oriented technologies. These practices can enhance efficiency and business insight, but they also present risks that our business policies and internal security controls may not keep pace with the speed of these changes. 
					</br></br>
					<span class="style2">We could be harmed by data loss or other security breaches which we may not be able to recover from.</span>
					</br>
					As a result of our services being web-based and the fact that we process, store and transmit large amounts of data, including personal information, for our customers, failure to prevent or mitigate data loss or other security breaches, including breaches of our vendors’ technology and systems, could expose us or our customers to a risk of loss or misuse of such information, adversely affect our operating results, result in litigation or potential liability for us and otherwise harm our business. We use third party technology and systems for a variety of reasons, including, without limitation, encryption and authentication technology, employee email, content delivery to customers, back-office support and other functions.. 
					</br></br>
					Computer malware, viruses, and computer hacking and phishing attacks have become more prevalent in our industry, have occurred on our systems in the past, and may occur on our systems in the future. Because of the nature of our business, we believe that we are a particularly attractive target for such attacks. Though it is difficult to determine what, if any, harm may directly result from any specific interruption or attack, any failure to maintain performance, reliability, security, and availability of our products and technical infrastructure. Any such failure may harm our reputation and our ability to retain existing users and attract new users. In addition, spammers attempt to use our products to send targeted and untargeted spam messages to users, which may embarrass or annoy users and make NeuroMama less user-friendly. We cannot be certain that the technologies and employees that we have to attempt to defeat spamming attacks will be able to eliminate all spam messages from being sent on our platform. As a result of spamming activities, our users may use NeuroMama less or stop using our products altogether.
					</br></br>
					<span class="style2">Privacy concerns relating to our technology could damage our reputation and deter current and potential users from using our products and services.</span>
					</br>
					From time to time, concerns are raised to regulators and others about whether search engines compromise the privacy of users and others. Concerns about, or regulatory actions involving  the generally accepted practices of the industry with regard to the collection, use, disclosure, or security of personal information or other privacy related matters, even if unfounded, could damage our reputation and adversely affect operating results. While we strive to comply with all applicable data protection laws and regulations, as well as our own posted privacy policies, the failure or perceived failure to comply may result, and in some cases has resulted, in inquiries and other proceedings or actions against us by government entities or others, or could cause us to lose users and customers, which could potentially have an adverse effect on our business.
					</br></br>
					In addition, as nearly all of our products and services will be web-based, the amount of data we intend to store for our users on our servers (including personal information) will be increasing over time.  Any systems failure or compromise of our security that results in the release of our users' data could seriously limit the adoption of our products and services, as well as harm our reputation and brand and, therefore, our business. We will continue to expend significant resources to protect against security breaches. The risk that these types of events could seriously harm our business is likely to increase as we expand the number of web-based products and services we offer, and operate in more countries.
					</br></br>
					Regulatory authorities around the world are considering a number of legislative and regulatory proposals concerning data protection. In addition, the interpretation of consumer and data protection laws in the U.S., Europe and elsewhere are often uncertain and in flux. It is possible that these laws may be interpreted and applied in a manner that is inconsistent with our data practices. If so, in addition to the possibility of fines, this could result in an order requiring that we change our data practices, which could have an adverse effect on our business and results of operations. Complying with these various laws could cause us to incur substantial costs or require us to change our business practices in a manner adverse to our business.
					</br></br>
					<span class="style2">We Face Risks Related to System Interruption and Lack of Redundancy</span>
					</br>
					We experience occasional system interruptions and delays that make our websites and services unavailable or slow to respond and prevent us from efficiently fulfilling orders or providing services to third parties, which may reduce our net sales and the attractiveness of our products and services. If we are unable to continually add software and hardware, effectively upgrade our systems and network infrastructure and take other steps to improve the efficiency of our systems, it could cause system interruptions or delays and adversely affect our operating results.
					</br></br>
					Our computer and communications systems and operations could be damaged or interrupted by fire, flood, power loss, telecommunications failure, earthquakes, acts of war or terrorism, acts of God, computer viruses, physical or electronic break-ins, and similar events or disruptions. Any of these events could cause system interruption, delays, and loss of critical data, and could prevent us from accepting and fulfilling customer orders and providing services, which could make our product and service offerings less attractive and subject us to liability. Our systems are not fully redundant and our disaster recovery planning may not be sufficient. In addition, we may have inadequate insurance coverage to compensate for any related losses. Any of these events could damage our reputation and be expensive to remedy.
					</br></br>
					<span class="style2">We are dependent on bleeding edge technology in our operations, and if our technology fails or we are unable to continue to invest in new technology, our business will be adversely affected.</span>
					</br>
					We have become increasingly dependent on technology initiatives to reduce costs and to enhance customer service in order to compete in the current business environment and to bring a unique experience to our users. For example, we have made and continue to make significant investments in our Frequent Search Rewards (FSR) program, our Socratic Method Search Alternative (SMSA), our Content Delivery Platform (CDP), web based applications, mobile device applications to access these platforms, and other related initiatives. The performance and reliability of the technology are critical to our ability to attract and retain customers and our ability to compete effectively. Because of the rapid pace of new developments, these initiatives will continue to require significant capital investments in our technology infrastructure. If we are unable to make these investments, our business and operations could be negatively affected.
					</br></br>
					<span class="style2">Our business is dependent on our ability to maintain and scale our technical infrastructure, and any significant disruption in our service could damage our reputation, result in a potential loss of users and engagement, and adversely affect our financial results. </span>
					</br>
					Our reputation and ability to attract, retain, and serve our users is dependent upon the reliable performance of NeuroMama and our underlying technical infrastructure. Our systems may not be adequately designed with the necessary reliability and redundancy to avoid performance delays or outages that could be harmful to our business. If NeuroMama is unavailable when users attempt to access it, or if it does not load as quickly as they expect, users may not return to our website as often in the future, or at all. As our user base and the amount and types of information shared on NeuroMama continue to grow, we will need an increasing amount of technical infrastructure, including network capacity, and computing power, to continue to satisfy the needs of our users. It is possible that we may fail to effectively scale and grow our technical infrastructure to accommodate these increased demands. In addition, our business may be subject to interruptions, delays, or failures resulting from earthquakes, adverse weather conditions, other natural disasters, power loss, terrorism, or other catastrophic events. 
					</br></br>
					A substantial portion of our network infrastructure is provided by third parties. Any disruption or failure in the services we receive from these providers could harm our ability to handle existing or increased traffic and could significantly harm our business. Any financial or other difficulties these providers face may adversely affect our business, and we exercise little control over these providers, which increases our vulnerability to problems with the services they provide. 
					</br></br>
					<span class="style2">We could experience unforeseen difficulties in building and operating key portions of our technical infrastructure.</span>
					</br>
					We have designed and built our own data centers and key portions of our technical infrastructure through which we serve our products, and we plan to continue to significantly expand the size of our infrastructure primarily through data centers and other projects. The infrastructure expansion we are undertaking is complex, and unanticipated delays in the completion of these projects or availability of components may lead to increased project costs, operational inefficiencies, or interruptions in the delivery or degradation of the quality of our products. In addition, there may be issues related to this infrastructure that are not identified during the testing phases of design and implementation, which may only become evident after we have started to fully utilize the underlying equipment, that could further degrade the user experience or increase our costs. Our products and internal systems rely on software that is highly technical, and if it contains undetected errors, our business could be adversely affected. Our products and internal systems rely on software that is highly technical and complex. In addition, our products and internal systems depend on the ability of our software to store, retrieve, process, and manage immense amounts of data. Our software has contained, and may now or in the future contain, undetected errors, bugs, or vulnerabilities. Some errors in our software may only be discovered after the code has been released for external or internal use. Errors or other design defects within our software may result in a negative experience for users and marketers who use our products, delay product introductions or enhancements, or result in measurement or billing errors. Any errors, bugs, or defects discovered in our software could result in damage to our reputation, loss of users, loss of revenue, or liability for damages, any of which could adversely affect our business and financial results. 
					</br></br>
					<span class="style2">The listing or sale by our users of pirated or counterfeit items may harm our business.</span>
					</br>
					As is the nature of our business we anticipate receiving communications alleging that certain items sold through our service by our users infringe third-party copyrights, trademarks and trade names, or other intellectual property rights. Although we have sought to work actively with the owners of intellectual property rights to eliminate listings offering infringing items on our websites, some rights owners will undoubtedly express the view that our efforts are insufficient. Content owners and other intellectual property rights owners have actively asserted their purported rights against online companies. In addition to litigation from rights owners, we may be subject to regulatory, civil or criminal proceedings and penalties if governmental authorities believe we have aided and abetted in the sale of counterfeit goods. While case law has seen some early success in defending against such litigation, more recent cases have been based, at least in part, on different legal theories than those of earlier cases, and there is no guarantee that we will be successful in defending against such litigation. Plaintiffs in recent cases have argued that we are not entitled to safe harbors under the Digital Millennium Copyright Act in the U.S. or as a hosting provider in the European Union under the Electronic Commerce Directive because of the alleged active nature of our involvement with our sellers, and that whether or not such safe harbors are available. We believe that the legal climate, especially in Europe, is becoming more adverse to our positions, which may require us to take actions which could lower our revenues, increase our costs, or make our websites and mobile platforms less convenient to our customers, which could materially harm our business. In addition, public perception that counterfeit or pirated items are commonplace on our sites, even if factually incorrect, would damage our reputation, lower the price our affiliates receive for their items and damage our business.
					</br></br>
					We are continuously seeking to improve and modify our efforts to eliminate counterfeit and pirated items through ongoing business initiatives designed to reduce bad buyer experiences and improve customer satisfaction and by responding to new patterns we are seeing among counterfeiters and others committing fraud on our users. Increased intermediation of transactions between buyers and sellers, which we generally refer to as NeuroZone, intended to achieve those goals may result in us being unable to rely, to the same extent that we have in the past, on hosting immunity and other secondary liability safe harbors when sued by users and rights owners over actions taken on our site by our users. While we are taking steps to mitigate this impact on our safe harbor defenses, we may be subject to more intellectual property litigation and may lose more cases as a result of these business model changes, which would adversely affect our business.
					</br></br>
					In addition, new laws have been proposed regulating Internet companies with respect to intellectual property issues. For example, ACTA and TPP are trade agreements that include international standards for enforcing intellectual property rights, including provisions regarding counterfeit goods and online piracy. The European Commission is considering revising the Intellectual Property Enforcement Directive, which could potentially increase our exposure to enforcement actions from rights owners. 
				</div>
			</div>
		</div>
	</body>
</html>