<html>
	<?php include 'header.php';?>
	<title>Risk Factors: Management</title>
	<body>
		<?php include 'navigation.php';?>
		<div id="PageContainerOuter">
			<div id="PageContainer">
				<div class="inner">
					<div class="style1">Risk Factors: Management</div>
					</br>
					<span class="style2">We have no operating history.</span>
					</br>
					We were formed principally to develop and operate NeuroMama.com. NeuroMama will be a new venture which has no history of operations. We cannot assure you that we will be able to attract a sufficient number of users, affiliates or advertisers to the Neuromama.com domain to make our operations profitable.
					</br></br>
					Our operations will be subject to the significant business, economic, regulatory and competitive uncertainties and contingencies frequently encountered by new businesses in competitive environments, many of which are beyond our control. Because we have no operating history, it may be more difficult for us to prepare for and respond to these types of risks and the risks described elsewhere in this prospectus than for a company with an established business and operating cash flow. If we are not able to manage these risks successfully, it could negatively impact our operations.
					</br></br>
					<span class="style2">Our Business Could Suffer if We Are Unsuccessful in Making, Integrating, and Maintaining Commercial Agreements, Strategic Alliances, and Other Business Relationships</span>
					</br>
					We provide services to other businesses through our affiliate programs and other commercial agreements, strategic alliances and business relationships. Under these agreements, we provide technology, fulfillment and other services, as well as enable sellers to offer products or services through our websites and power their websites. These arrangements are complex and will require substantial personnel and resource commitments by us, which may limit the agreements we are able to enter into and our ability to integrate and deliver services under them. If we fail to implement, maintain, and develop the components of these commercial relationships, which may include fulfillment, customer service, inventory management, tax collection, payment processing, licensing of third-party software, hardware, and content, and engaging third parties to perform hosting and other services, these initiatives may not be viable. The amount of compensation we receive under certain of these agreements is partially dependent on the volume of the other company’s sales. Therefore, if the other company’s offering is not successful, the compensation we receive may be lower than expected or the agreement may be terminated. Moreover, we may not be able to enter into additional commercial relationships and strategic alliances on favorable terms. We also may be subject to claims from businesses to which we provide these services if we are unsuccessful in implementing, maintaining or developing these services.
					</br></br>
					As our agreements terminate, we may be unable to renew or replace these agreements on comparable terms, or at all. We may in the future enter into amendments on less favorable terms or encounter parties that have difficulty meeting their contractual obligations to us, which could adversely affect our operating results.
					</br></br>
					<span class="style2">Our Business Could Suffer if We Are Unsuccessful in Making, Integrating, and Maintaining Acquisitions and Investments</span>
					</br>
					We have invested in a number of companies, and we may acquire or invest in or enter into joint ventures with additional companies. As a result of future acquisitions or mergers, we might need to issue additional equity securities, spend our cash, or incur debt, contingent liabilities, or amortization expenses related to intangible assets, any of which could reduce our profitability and harm our business. In addition, valuations supporting our acquisitions and strategic investments could change rapidly given the current global economic climate. We could determine that such valuations have experienced impairments or other-than-temporary declines in fair value which could adversely impact our financial results.
					</br></br>
					<span class="style2">We Are Subject to Payments-Related Risks</span>
					</br>
					We will accept payments using a variety of methods, including credit card, debit card, credit accounts (including promotional financing), gift certificates, direct debit from a customer’s bank account, consumer invoicing, physical bank check FSR Points, and payment upon delivery. As we offer new payment options to our customers, we may be subject to additional regulations, compliance requirements, and fraud. For certain payment methods, including credit and debit cards, we pay interchange and other fees, which may increase over time and raise our operating costs and lower profitability. We rely on third parties to provide payment processing services, including the processing of credit cards, debit cards, electronic checks, and promotional financing, and it could disrupt our business if these companies become unwilling or unable to provide these services to us. We are also subject to payment card association operating rules, including data security rules, certification requirements and rules governing electronic funds transfers, which could change or be reinterpreted to make it difficult or impossible for us to comply. If we fail to comply with these rules or requirements, or if our data security systems are breached or compromised, we may be liable for card issuing banks’ costs, subject to fines and higher transaction fees and lose our ability to accept credit and debit card payments from our customers, process electronic funds transfers, or facilitate other types of online payments, and our business and operating results could be adversely affected. We may offer co-branded credit cards. If one or more of these agreements are terminated and we are unable to replace them on similar terms, or at all, it could adversely affect our operating results.
					</br></br>
					<span class="style2">Our business depends on our ability to attract and retain talented employees.</span>
					</br>
					Our business is based on successfully attracting and retaining talented employees. The market for highly skilled workers and leaders in our industry is extremely competitive. We are limited in our ability to recruit internationally by restrictive domestic immigration laws. If we are less successful in our recruiting efforts, or if we are unable to retain key employees, our ability to develop and deliver successful products and services may be adversely affected. Effective succession planning is also important to our long-term success. Failure to ensure effective transfer of knowledge and smooth transitions involving key employees could hinder our strategic planning and execution.
					</br></br>
					<span class="style2">Delays in product development schedules may adversely affect our revenue.</span>
					</br>
					The development of software products is a complex and time-consuming process. New products and enhancements to existing products can require long development and testing periods. Our increasing focus on devices and cloud-based services also presents new and complex development issues. Significant delays in new product or service releases or significant problems in creating new products or services could adversely affect our revenue.
					</br></br>
					<span class="style2">If We Do Not Successfully Operate Our Customer Care Centers, Our Business Could Be Harmed</span>
					</br>
					If we do not adequately predict customer demand or otherwise optimize and operate our fulfillment centers successfully, it could result in excess or insufficient inventory or fulfillment capacity, result in increased costs, impairment charges, or both, or harm our business in other ways. A failure to optimize inventory will increase our net shipping cost by requiring long-zone or partial shipments. Orders from our website are fulfilled primarily from a single location, and we have only a limited ability to reroute orders to third parties for drop-shipping. We may be unable to adequately staff our fulfillment and customer service centers. As we continue to add fulfillment and warehouse capability or add new businesses with different fulfillment requirements, our fulfillment network becomes increasingly complex and operating it becomes more challenging. If the other businesses on whose behalf we perform inventory fulfillment services deliver product to our fulfillment centers in excess of forecasts, we may be unable to secure sufficient storage space and may be unable to optimize our fulfillment centers. There can be no assurance that we will be able to operate our network effectively.
					</br></br>
					We rely on a limited number of shipping companies to deliver inventory to us and completed orders to our customers. If we are not able to negotiate acceptable terms with these companies or they experience performance problems or other difficulties, it could negatively impact our operating results and customer experience. In addition, our ability to receive inbound inventory efficiently and ship completed orders to customers also may be negatively affected by inclement weather, fire, flood, power loss, earthquakes, labor disputes, acts of war or terrorism, acts of God and similar factors.
					</br></br>
					Third parties either drop-ship or otherwise fulfill an increasing portion of our customers’ orders, and we are increasingly reliant on the reliability, quality and future procurement of their services. Under some of our commercial agreements, we maintain the inventory of other companies, thereby increasing the complexity of tracking inventory and operating our fulfillment centers. Our failure to properly handle such inventory or the inability of these other companies to accurately forecast product demand would result in unexpected costs and other harm to our business and reputation.
					</br></br>
					<span class="style2">The Loss of Key Senior Management Personnel Could Negatively Affect Our Business</span>
					</br>
					We depend on our senior management and other key personnel. We do not have “key person” life insurance policies. The loss of any of our executive officers or other key employees could harm our business. 
					</br></br>
					<span class="style2">We Face Significant Inventory Risk</span>
					</br>
					In addition to risks described elsewhere in this section relating to fulfillment center and inventory optimization by us and third parties, we are exposed to significant inventory risks that may adversely affect our operating results as a result of seasonality, new product launches, rapid changes in product cycles and pricing, defective merchandise, changes in consumer demand and consumer spending patterns, changes in consumer tastes with respect to our products and other factors. We endeavor to accurately predict these trends and avoid overstocking or understocking products we manufacture and/or sell. Demand for products, however, can change significantly between the time inventory or components are ordered and the date of sale. In addition, when we begin selling or manufacturing a new product, it may be difficult to establish vendor relationships, determine appropriate product or component selection, and accurately forecast demand. The acquisition of certain types of inventory or components may require significant lead-time and prepayment and they may not be returnable. We carry a broad selection and significant inventory levels of certain products, such as consumer electronics, and we may be unable to sell products in sufficient quantities or during the relevant selling seasons. Any one of the inventory risk factors set forth above may adversely affect our operating results.
					</br></br>
					<span class="style2">Improper disclosure of personal data could result in liability and harm our reputation.</span>
					</br>
					As we continue to grow the number and scale of our cloud-based offerings, we store and process increasingly large amounts of personally identifiable information of our customers. At the same time, the continued occurrence of high-profile data breaches provides evidence of an external environment increasingly hostile to information security. This environment demands that we continuously improve our design and coordination of security controls across our business groups and geographies. Despite these efforts, it is possible our security controls over personal data, our training of employees and vendors on data security, and other practices we follow may not prevent the improper disclosure of personally identifiable information that we or our vendors store and manage. Improper disclosure of this information could harm our reputation, lead to legal exposure to customers, or subject us to liability under laws that protect personal data, resulting in increased costs or loss of revenue. Our software products and services enable our customers to store and process personal data on premise or, increasingly, in a cloud-based environment we host. We believe consumers using our email, messaging, storage, sharing, and social networking services will increasingly want efficient, centralized methods of choosing their privacy preferences and controlling their data. Perceptions that our products or services do not adequately protect the privacy of personal information could inhibit sales of our products or services.
					</br></br>
					<span class="style2">Acquisitions and investments could result in operating difficulties, dilution, and other harmful consequences that may adversely impact our business and results of operations.</span>
					</br>
					Acquisitions are an important element of our overall corporate strategy and use of capital, and we expect to partake in several acquisitions per year. These transactions could be material to our financial condition and results of operations. We also expect to continue to evaluate and enter into discussions regarding a wide array of strategic transactions. The process of integrating an acquired company, business, or technology will create unforeseen operating difficulties and expenditures. The areas where we face risks include:
					</br></br>
					<ul class="simple">
						<li>Diversion of management time and focus from operating our business to acquisition integration challenges.</li>
						<li>Failure to successfully further develop the acquired business or technology.</li>
						<li>Implementation or remediation of controls, procedures, and policies at the acquired company.</li>
						<li>Integration of the acquired company's accounting, human resource, and other administrative systems, and coordination of product, engineering, and sales and marketing functions.</li>
						<li>Transition of operations, users, and customers onto our existing platforms.</li>
						<li>Failure to obtain required approvals on a timely basis, if at all, from governmental authorities, or conditions placed upon approval, under competition and antitrust laws which could, among other things, delay or prevent us from completing a transaction, or otherwise restrict our ability to realize the expected financial or strategic goals of an acquisition.</li>
						<li>In the case of foreign acquisitions, the need to integrate operations across different cultures and languages and to address the particular economic, currency, political, and regulatory risks associated with specific countries.</li>
						<li>Cultural challenges associated with integrating employees from the acquired company into our organization, and retention of employees from the businesses we acquire.</li>
						<li>Liability for activities of the acquired company before the acquisition, including patent and trademark infringement claims, violations of laws, commercial disputes, tax liabilities, and other known and unknown liabilities.</li>
						<li>Litigation or other claims in connection with the acquired company, including claims from terminated employees, customers, former stockholders, or other third parties.</li>
					</ul>
					</br>
					Our failure to address these risks or other problems encountered in connection with our past or future acquisitions and investments could cause us to fail to realize the anticipated benefits of such acquisitions or investments, incur unanticipated liabilities, and harm our business generally
					</br></br>
					Future acquisitions could also result in dilutive issuances of our equity securities, the incurrence of debt, contingent liabilities, or amortization expenses, or impairment of goodwill, and restructuring charges, any of which could harm our financial condition or results. Also, the anticipated benefit of many of our acquisitions may not materialize.</li>
					</br></br>
					<span class="style2">Improper access to or disclosure of our users' information, or violation of our terms of service or policies, could harm our reputation and adversely affect our business.</span>
					</br>
					Our efforts to protect the information that our users have chosen to share using NeuroMama may be unsuccessful due to the actions of third parties, software bugs or other technical malfunctions, employee error or malfeasance, or other factors. In addition, third parties may attempt to fraudulently induce employees or users to disclose information in order to gain access to our data or our users' data. If any of these events occur, our users' information could be accessed or disclosed improperly. Our Data Use Policy governs the use of information that users have chosen to share using NeuroMama and how that information may be used by us and third parties. Some Platform developers may store information provided by our users through apps on the NeuroMama Platform or websites integrated with NeuroMama. If these third parties or Platform developers fail to adopt or adhere to adequate data security practices or fail to comply with our terms and policies, or in the event of a breach of their networks, our users' data may be improperly accessed or disclosed. 
					</br></br>
					Any incidents involving unauthorized access to or improper use of the information of our users or incidents involving violation of our terms of service or policies, including our Data Use Policy, could damage our reputation and our brand and diminish our competitive position. In addition, the affected users or government authorities could initiate legal or regulatory action against us in connection with such incidents, which could cause us to incur significant expense and liability or result in orders or consent decrees forcing us to modify our business practices. Any of these events could have a material and adverse effect on our business, reputation, or financial results. 
					</br></br>
					<span class="style2">If we are unable to protect our intellectual property, the value of our brand and other intangible assets may be diminished, and our business may be adversely affected. </span>
					</br>
					We rely and expect to continue to rely on a combination of confidentiality and license agreements with our employees, consultants, and third parties with whom we have relationships, as well as trademark, copyright, patent, trade secret, and domain name protection laws, to protect our proprietary rights. In the United States and internationally, we have filed various applications for protection of certain aspects of our intellectual property, and we currently hold a number of issued patents in multiple jurisdictions and have acquired patents and patent applications from third parties. In the future we may acquire additional patents or patent portfolios, which could require significant cash expenditures. Third parties may knowingly or unknowingly infringe our proprietary rights, third parties may challenge proprietary rights held by us, and pending and future trademark and patent applications may not be approved. In addition, effective intellectual property protection may not be available in every country in which we operate or intend to operate our business. In any or all of these cases, we may be required to expend significant time and expense in order to prevent infringement or to enforce our rights. Although we have taken measures to protect our proprietary rights, there can be no assurance that others will not offer products or concepts that are substantially similar to ours and compete with our business. In addition, we regularly contribute software source code under open source licenses and have made other technology we developed available under other open licenses, and we include open source software in our products. If the protection of our proprietary rights is inadequate to prevent unauthorized use or appropriation by third parties, the value of our brand and other intangible assets may be diminished and competitors may be able to more effectively mimic our service and methods of operations. Any of these events could have an adverse effect on our business and financial results.
					</br></br>
					<span class="style2">Certain of our user metrics are subject to inherent challenges in measurement, and real or perceived inaccuracies in such metrics may harm our reputation and negatively affect our business. </span>
					</br></br>
					The numbers of our Frequent Search Rewards FSRs and average revenue per user (ARPU) are calculated using internal company data based on the activity of user accounts. While these numbers are based on what we believe to be reasonable estimates of our user base for the applicable period of measurement, there are inherent challenges in measuring usage of our products across large online and mobile populations around the world. For example, there may be individuals who maintain one or more accounts or fail to log in prior to doing a search. We estimate, for example, that "duplicate" accounts (an account that a user maintains in addition to his or her principal account) could represent approximately 5.0% of our user base. We also seek to identify "false" accounts, which we divide into two categories: (1) user-misclassified accounts, where users have created personal profiles for a business, organization, or non-human entity such as a pet (2) undesirable accounts, which represent user profiles that we determine are intended to be used for purposes that violate our terms of service, such as spamming. We estimate user-misclassified accounts could represent approximately 1.3% of our worldwide user base and undesirable accounts may have represented approximately 0.9% of our worldwide user base. 
					</br></br>
					Some of our metrics could at times be affected by applications on certain mobile devices that automatically contact our servers for regular updates with no user action involved, and this activity can cause our system to count the user associated with such a device as an active user on the day such contact occurs. The impact of this automatic activity on our metrics varied by geography because mobile usage varies in different regions of the world. In addition, data regarding the geographic location of our users is estimated based on a number of factors, such as the user's IP address and self-disclosed location. These factors may not always accurately reflect the user's actual location. For example, a mobile-only user may appear to be accessing our servers from the location of the proxy server that the user connects to rather than from the user's actual location. The methodologies used to measure user metrics may also be susceptible to algorithm or other technical errors. Our estimates for revenue by user location and revenue by user device are also affected by these factors. We regularly review and may adjust our processes for calculating these metrics to improve their accuracy. In addition, our estimates will differ from estimates published by third parties due to differences in methodology. For example, some third parties are not able to accurately measure mobile users or do not count mobile users for certain user groups or at all in their analyses. If marketers, developers, or investors do not perceive our user metrics to be accurate representations of our user base, or if we discover material inaccuracies in our user metrics, our reputation may be harmed and marketers and developers may be less willing to allocate their budgets or resources to NeuroMama, which could negatively affect our business and financial results. 
				</div>
			</div>
		</div>
	</body>
</html>