<html>
	<?php include 'header.php';?>
	<title>Risk Factors: Regulation</title>
	<body>
		<?php include 'navigation.php';?>
		<div id="PageContainerOuter">
			<div id="PageContainer">
				<div id="HomeGalleryNavigation">
                    
                    <?php
                        include 'Banners/Banner8/index.html'; 
                    ?>

                </div>
				<div class="inner">
					<div class="style1">Risk Factors: Regulation</div>
					</br>
					<span class="style2">A variety of new and existing U.S. and foreign laws could subject us to claims or otherwise harm our business.</span>
					</br>
					We are subject to numerous U.S. and foreign laws and regulations covering a wide variety of subject matters. New laws and regulations (or new interpretations of existing laws and regulations) may also impact our business. The costs of compliance with these laws and regulations are high and are likely to increase in the future. Any failure on our part to comply with these laws and regulations can result in negative publicity and diversion of management time and effort and may subject us to significant liabilities and other penalties.
					</br></br>
					Furthermore, many of these laws were adopted prior to the advent of the internet and related technologies and, as a result, do not contemplate or address the unique issues of the internet and related technologies. The laws that do reference the internet are being interpreted by the courts, but their applicability and scope remain uncertain. For example, the laws relating to the liability of providers of online services are currently unsettled both within the U.S. and abroad. Claims have also been, or may be, threatened and filed against us under both U.S. and foreign laws for defamation, invasion of privacy and other tort claims, unlawful activity, patent, copyright and trademark infringement, or other theories based on the nature and content of the materials searched and the ads posted by our users, our products and services, or content generated by our users. Moreover, recent amendments to U.S. patent laws may affect the ability of companies, including us, to protect their innovations and defend against claims of patent infringement.
					</br></br>
					In addition, the Digital Millennium Copyright Act has provisions that limit, but do not necessarily eliminate, our liability for caching or hosting, or for listing or linking to, third-party websites that include materials that infringe copyrights or other rights, so long as we comply with the statutory requirements of this act. Any future legislation impacting these safe harbors may adversely impact us. Various U.S. and international laws restrict the distribution of materials considered harmful to children and impose additional restrictions on the ability of online services to collect information from minors. In the area of data protection, many states have passed laws requiring notification to users when there is a security breach for personal data, such as California’s Information Practices Act. We face similar risks and costs as our products and services are offered in international markets and may be subject to additional regulations.
					</br></br>
					<span class="style2">We are subject to increased regulatory scrutiny that may negatively impact our business.</span>
					</br>
					As our company expands into a variety of new fields we can expect new regulatory issues, and we have experienced increased regulatory scrutiny as we have grown. Our search suppliers and partners also have or may come under regulatory scrutiny. There are several layers of regulatory bodies we must navigate and cooperate with such as the European Commission (EC), other international regulatory authorities, Federal legislation and State compliance. Legislators and regulators, including those conducting investigations in the U.S. and Europe, may make legal and regulatory changes, or interpret and apply existing laws, in ways that make our products and services less useful to our users, require us to incur substantial costs, expose us to unanticipated civil or criminal liability, or cause us to change our business practices. These changes or increased costs could negatively impact our business and results of operations in material ways.
					</br></br>
					<span class="style2">We May be Subject to Risks Related to Government Contracts and Related Procurement Regulations</span>
					</br>
					Any contracts we have with or may have with U.S., as well as state, local and foreign, government entities are subject to various procurement regulations and other requirements relating to their formation, administration and performance. We may be subject to audits and investigations relating to our government contracts and any violations could result in various civil and criminal penalties and administrative sanctions, including termination of contract, refunding or suspending of payments, forfeiture of profits, payment of fines and suspension or debarment from future government business. In addition, such contracts may provide for termination by the government at any time, without cause.
					</br></br>
				</div>
			</div>
		</div>
	</body>
</html>